ppt_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from .views import (
	converttexttoppt_func,
	import_file,
	create_outline,
	download_func,
	slide_templates_func
	)

urlpatterns = [
	url(r"^$", converttexttoppt_func, name="converttexttoppt"),
	url(r'^download/(?P<slug>[\w-]+)/$', download_func, name='download'),
	url(r'^import-file/$', import_file, name='import_file'),
	url(r'^create-outline/$', create_outline, name='create_outline'),
	url(r'^slide-templates/$', slide_templates_func, name='slide_templates'),
]

tiny_apps/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings

from accounts.views import (login_view, register_view, logout_view)

admin.autodiscover()

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns(
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
    url("^convert-to-ppt/", include("ppt_app.urls", namespace="txttoppt")),
    url("^merge_xlsx/", include("xlsx_app.urls", namespace="main_home")),
    url("^login/", login_view, name="login"),
    url("^logout/", logout_view, name="logout"),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += [
        url('^i18n/$', set_language, name='set_language'),
    ]

urlpatterns += [
    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.pages.views.page, {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.blog.views.blog_post_list, name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    url("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

]

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

templates/base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
{% load pages_tags mezzanine_tags i18n staticfiles %}


<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
<meta name="description" content="{% block meta_description %}{% endblock %}">
<title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>

<link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

{% ifinstalled mezzanine.blog %}
<link rel="alternate" type="application/rss+xml" title="RSS" href="{% url "blog_post_feed" "rss" %}">
<link rel="alternate" type="application/atom+xml" title="Atom" href="{% url "blog_post_feed" "atom" %}">
{% endifinstalled %}

{% compress css %}
<!-- custom.css is a customized css -->
<link rel="stylesheet" href="{% static "css/custom.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
<link rel="stylesheet" href="{% static "css/mezzanine.css" %}">
<link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}">
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/bootstrap-rtl.css" %}">
{% endif %}
{% ifinstalled cartridge.shop %}
<link rel="stylesheet" href="{% static "css/cartridge.css" %}">
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="{% static "css/cartridge.rtl.css" %}">
{% endif %}
{% endifinstalled %}
{% block extra_css %}{% endblock %}
{% endcompress %}

{% compress js %}
<script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script>
<script src="{% static "js/bootstrap.js" %}"></script>
<script src="{% static "js/bootstrap-extras.js" %}"></script>

<!-- custom js -->
<!-- textarea_autoresize_custom.js is a customized javascript for autoresize textarea -->
<script src="{% static "js/textarea_autoresize_custom.js" %}"></script>

{% block extra_js %}{% endblock %}
{% endcompress %}

<!--[if lt IE 9]>
<script src="{% static "js/html5shiv.js" %}"></script>
<script src="{% static "js/respond.min.js" %}"></script>
<![endif]-->

{% block extra_head %}{% endblock %}
</head>


<body id="{% block body_id %}body{% endblock %}">
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">{% trans "Toggle Navigation" %}</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% block navbar_title %}
                {% if settings.SITE_TITLE %}<a class="navbar-brand" href="/">{{ settings.SITE_TITLE }}</a>{% endif %}
                {% if settings.SITE_TAGLINE %}<p class="navbar-text visible-lg">{{ settings.SITE_TAGLINE }}</p>{% endif %}
                {% endblock%}
            </div>
            <div class="navbar-collapse collapse">  
                {% if request.user.is_authenticated %}  
            	<ul class="nav navbar-nav navbar-right">         		
	                {% block navbar_dropdown_menu %}{% page_menu "pages/menus/dropdown.html" %}{% endblock%}
                    <li><a href="{% url 'logout' %}">Logout</a></li>
                </ul>
                {% endif %}  
            </div>
            
        </div>
    </div>
    <!-- end of navbar -->

    {% block content %}

    {% endblock content %}

    <footer>
        <div class="container">
        {% page_menu "pages/menus/footer.html" %}

        <div class="row">
        <p class="site-info text-center">
            {% trans "Powered by" %}
            <a href="http://mezzanine.jupo.org">Mezzanine</a>{% ifinstalled cartridge.shop %},
            <a href="http://cartridge.jupo.org">Cartridge</a>{% endifinstalled %}
            {% trans "and" %}
            <a href="http://www.djangoproject.com">Django</a>
            <span class="separator">|</span>
            {% trans "Theme by" %} <a target="_blank" href="http://getbootstrap.com">Bootstrap</a>
            {% ifinstalled mezzanine.mobile %}
            <span class="separator">|</span>
            <a href="{% url "set_device" "mobile" %}?next={{ request.path }}">{% trans "View Mobile Site" %}</a>
            {% endifinstalled %}
        </p>
        </div>
        </div>
    </footer>

</body>

<!-- allows the textarea in "creatoutline" page to capture the "tab" key presses
and prevent to tab into the next element in the page -->
<script type="text/javascript">
    
    $(document).delegate('#outline', 'keydown', function(e) { 
      var keyCode = e.keyCode || e.which; 

      if (keyCode == 9) { 
        e.preventDefault(); 
        var start = $(this).get(0).selectionStart;
        var end = $(this).get(0).selectionEnd;

        // set textarea value to: text before caret + tab + text after caret
        $(this).val($(this).val().substring(0, start)
                    + "\t"
                    + $(this).val().substring(end));

        // put caret at right position again
        $(this).get(0).selectionStart = 
        $(this).get(0).selectionEnd = start + 1;

        // auto resize vertically

      } 

      
    });

    // text area >> create outline by editor
    $(function(){
        $('.normal').autosize();
        $('.animated').autosize({append: "\n"});
    });

    // options for which slide template to use
    $(document).ready(function() {
        $("#user_template_div").hide();
        $("#preloaded_template_div").hide();
        $("#template_option_1").click(function() {
            
            $("#user_template_div").hide()
            $("#preloaded_template_div").fadeIn("slow")
        });
        $("#template_option_0").click(function() {
            
            $("#preloaded_template_div").hide()
            $("#user_template_div").fadeIn("slow")
        });
       
    });

</script>

</html>
<!-- 
    # <input id="radio_preloaded_templates" type="radio" checked="cheked" name="template" value="0">    Use Preloaded Templates
    # <input id ="radio_user_templates" type="radio" name="template" value="1"> Upload Own Templates
 -->

templates/base_base.html
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
{% load pages_tags mezzanine_tags i18n staticfiles %}

<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <title>{% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}</title>
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}">

    {% ifinstalled mezzanine.blog %}
    <link rel="alternate" type="application/rss+xml" title="RSS" href="{% url "blog_post_feed" "rss" %}">
    <link rel="alternate" type="application/atom+xml" title="Atom" href="{% url "blog_post_feed" "atom" %}">
    {% endifinstalled %}

    {% compress css %}
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "css/mezzanine.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-theme.css" %}">
    {% if LANGUAGE_BIDI %}
    <link rel="stylesheet" href="{% static "css/bootstrap-rtl.css" %}">
    {% endif %}
    {% ifinstalled cartridge.shop %}
    <link rel="stylesheet" href="{% static "css/cartridge.css" %}">
    {% if LANGUAGE_BIDI %}
    <link rel="stylesheet" href="{% static "css/cartridge.rtl.css" %}">
    {% endif %}
    {% endifinstalled %}
    {% block extra_css %}{% endblock %}
    {% endcompress %}

    {% compress js %}
    <script src="{% static "mezzanine/js/"|add:settings.JQUERY_FILENAME %}"></script>
    <script src="{% static "js/bootstrap.js" %}"></script>
    <script src="{% static "js/bootstrap-extras.js" %}"></script>
    {% block extra_js %}{% endblock %}
    {% endcompress %}

    <!--[if lt IE 9]>
    <script src="{% static "js/html5shiv.js" %}"></script>
    <script src="{% static "js/respond.min.js" %}"></script>
    <![endif]-->

    {% block extra_head %}{% endblock %}
</head>

<body id="{% block body_id %}body{% endblock %}">

    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">{% trans "Toggle Navigation" %}</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {% block navbar_title %}
                {% if settings.SITE_TITLE %}<a class="navbar-brand" href="/">{{ settings.SITE_TITLE }}</a>{% endif %}
                {% if settings.SITE_TAGLINE %}<p class="navbar-text visible-lg">{{ settings.SITE_TAGLINE }}</p>{% endif %}
                {% endblock%}
            </div>
            <div class="navbar-collapse collapse">
                {% block navbar_search_form %}{% search_form "all" %}{% endblock %}
                {% block navbar_dropdown_menu %}{% page_menu "pages/menus/dropdown.html" %}{% endblock%}
            </div>
        </div>
    </div>

    <div class="container">

    {% nevercache %}
    {% if messages %}
    <div class="messages">
    {% for message in messages %}
    <div class="alert alert-dismissable alert-{{ message.tags }}" data-alert="alert">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    </div>
    {% endif %}
    {% endnevercache %}

    <h1>{% block title %}{% endblock %}</h1>

    <ul class="breadcrumb">
    {% spaceless %}
    {% block breadcrumb_menu %}{% page_menu "pages/menus/breadcrumb.html" %}{% endblock %}
    {% endspaceless %}
    </ul>

    </div>

    <div class="container">
        <div class="row">

        <div class="col-md-2 left">
            {% block left_panel %}
            <div class="panel panel-default tree">{% page_menu "pages/menus/tree.html" %}</div>
            {% endblock %}
        </div>

        <div class="col-md-7 middle">
            {% block main %}{% endblock %}
        </div>

        <div class="col-md-3 right">
            {% nevercache %}
            {% include "includes/language_selector.html" %}
            {% include "includes/user_panel.html" %}
            {% endnevercache %}
            <div class="panel panel-default">
            <div class="panel-body">
            {% block right_panel %}
            {% ifinstalled mezzanine.twitter %}
            {% include "twitter/tweets.html" %}
            {% endifinstalled %}
            {% endblock %}
            </div>
            </div>
        </div>

        </div>
    </div>

    <footer>
        <div class="container">
        {% page_menu "pages/menus/footer.html" %}

        <div class="row">
        <p class="site-info text-center">
            {% trans "Powered by" %}
            <a href="http://mezzanine.jupo.org">Mezzanine</a>{% ifinstalled cartridge.shop %},
            <a href="http://cartridge.jupo.org">Cartridge</a>{% endifinstalled %}
            {% trans "and" %}
            <a href="http://www.djangoproject.com">Django</a>
            <span class="separator">|</span>
            {% trans "Theme by" %} <a target="_blank" href="http://getbootstrap.com">Bootstrap</a>
            {% ifinstalled mezzanine.mobile %}
            <span class="separator">|</span>
            <a href="{% url "set_device" "mobile" %}?next={{ request.path }}">{% trans "View Mobile Site" %}</a>
            {% endifinstalled %}
        </p>
        </div>
        </div>
    </footer>

    {% block footer_js %}
    {% include "includes/footer_scripts.html" %}
    {% endblock %}

</body>
</html>

templates/download_page_ppt.html
{% extends 'base.html' %}
{% block title %} {{instance.title}} | {{block.super}} {% endblock title %}


{% block content %}

<div id="container">
<br><br>
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">			
			<div class="col-sm-6 col-sm-offset-3">			
				{% if messages %}
					{% for message in messages %}
					    <h4 {% if message.tags %} class="{{ message.tags }} text-align-center"{% endif %}>{{ message }}</h4>
					{% endfor %}
				{% endif %}
				</hr>
				<p><b>Filename:</b> <br> {{name}}</p>
				<a href="{{ MEDIA_URL }}/{{name}}" class="btn btn-block btn-success"><span class="glyphicon glyphicon-cloud-download"></span> Download Presentation</a>
			</div>
		</div>
	</div>
</div> 
<!-- end of class container -->

{% endblock content %}

templates/download_page_xlsx.html
{% extends 'base.html' %}
{% block title %} {{instance.title}} | {{block.super}} {% endblock title %}


{% block content %}

<div id="container">
<br><br>
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">			
			<div class="col-sm-6 col-sm-offset-3">			
				{% if messages %}
					{% for message in messages %}
					    <h4 {% if message.tags %} class="{{ message.tags }} text-align-center"{% endif %}>{{ message }}</h4>
					{% endfor %}
				{% endif %}
				</hr>
				<p><b>Filename:</b> <br> {{name}}</p>
				<a href="{{ MEDIA_URL }}/merged.csv" class="btn btn-block btn-success"><span class="glyphicon glyphicon-cloud-download"></span> Download CSV</a>
			</div>
		</div>
	</div>
</div> 
<!-- end of class container -->

{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block meta_title %}{% trans "Home" %}{% endblock %}
{% block title %}{% trans "Home" %}{% endblock %}


{% block breadcrumb_menu %}
<li class="active">{% trans "Home" %}</li>
{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-">
			
   		{% if request.user.is_authenticated %}
   			<center><h1>Hello! You are now logged in.</h1></center>
   		{% else %}
   			<div class="col-md-6 col-md-offset-3">
   			<div class="form-group">
   			<h3>An account is necessary to use the services!</h3><hr>
				<div class="col-md-6">
				<h6 class="lead">Oh here you are again.<br>Enjoying your stay here?</h6>
   				<a href="{%url 'login' %}" class="btn btn-block btn-primary">Login</a>
				</div>
				<div class="col-md-6">
				<h6 class="lead">Oh! A new fella. Wanna joing us? </h6>
   				<a href="#register" class="btn btn-block btn-warning">Register</a>
				</div>
   			</div>
   			</div>

   		{% endif %}
   		
		</div>
	</div>
</div>
{% endblock content %}

templates/index_base.html
{% extends "base.html" %}
{% load i18n %}

{% block meta_title %}{% trans "Home" %}{% endblock %}
{% block title %}{% trans "Home" %}{% endblock %}

{% block breadcrumb_menu %}
<li class="active">{% trans "Home" %}</li>
{% endblock %}

{% block main %}
{% blocktrans %}
<h2>Congratulations!</h2>
<p>
    Welcome to your new Mezzanine powered website.
    Here are some quick links to get you started:
</p>
<ul>
    <li><a href="/admin/">Log in to the admin interface</a></li>
    <li><a href="http://mezzanine.jupo.org/docs/content-architecture.html">Creating custom page types</a></li>
    <li><a href="http://mezzanine.jupo.org/docs/frequently-asked-questions.html#templates">Modifying HTML templates</a></li>
    <li><a href="http://mezzanine.jupo.org/docs/frequently-asked-questions.html#why-isn-t-the-homepage-a-page-object-i-can-edit-via-the-admin">Changing this homepage</a></li>
    <li><a href="http://mezzanine.jupo.org/docs/frequently-asked-questions.html">Other frequently asked questions</a></li>
    <li><a href="http://mezzanine.jupo.org/docs/configuration.html#default-settings">Full list of settings</a></li>
    <li><a href="http://mezzanine.jupo.org/docs/deployment.html">Deploying to a production server</a></li>
</ul>
{% endblocktrans %}
{% endblock %}

templates/invalid_input.html
{% extends "base.html" %}

{% block content %}
<div class="modal fade" id="downloadModal">
  <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <p class="modal-title lead">Download CSV File</p>
        </div>

        <div class="modal-body">
          <button class="btn btn-block btn-success"><span class="glyphicon glyphicon-cloud-download"></span> Download</button>
        </div>
      </div>
  </div>
</div>
{% endblock content %}

templates/login_form.html
{% extends "base.html" %}
{% load i18n %}

<!-- use in forms -->
{% load bootstrap %} 

{% block meta_title %}{% trans "Home" %}{% endblock %}
{% block title %}{% trans "Home" %}{% endblock %}

{% block content %}
<div class="container">     
  <div class="row form">
    <div class="col-sm-6 col-sm-offset-3">
      <form  role="form" method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
        <br>
        {% if messages %}
          {% for message in messages %}
              <h4 {% if message.tags %} class="{{ message.tags }} text-align-center"{% endif %}>{{ message }}</h4>
          {% endfor %}
        {% endif %}
        <br>
        <h1>Login</h1>
        <hr>
        <div class="form-group">
          {{ form | bootstrap}}<br>
          <button type="submit" class = "btn btn-primary btn-block"><span class="glyphicon glyphicon-login"></span> Login</button>     <br>
          <a href="#">Forgot password?</a>  
        </div>  
      </form> 
     
    </div>
  </div>
</div>
{% endblock content %}

templates/slide_templates.html
{% extends "base.html" %}
{% load i18n %}

<!-- use in forms -->
{% load bootstrap %} 

{% block meta_title %}{% trans "Choose a template" %}{% endblock %}

{% block content %}


<div class="container">
    <br>

    <h1>Choose template for your presentation</h1>

    <hr>
    <div id="main_area">

        <div class="row">
            <form  role="form" method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
                <div class="form-group">
                    <!-- <button type="submit" class = "btn btn-primary btn-block" role="button" data-toggle="modal" data-target="#downloadModal"><span class="glyphicon glyphicon-cloud-upload"></span> Convert to CSV</button> -->
                        {% if messages %}
                        {% for message in messages %}
                            <h4 {% if message.tags %} class="{{ message.tags }} text-align-center"{% endif %}>{{ message }}</h4>
                        {% endfor %}
                        {% endif %}

                        <h1>Slide Templates Here!</h1>
                        
                        <a href="{% url 'txttoppt:slide_templates' %}" class="btn btn-primary btn-block">Continue</a>
                        <!-- <button type="submit" class = "btn btn-primary btn-block"><span class="glyphicon glyphicon-circle-arrow-right"></span> Convert to PowerPoint Presentation</button>              -->
                </div>  
            </form>
        </div>
        <!-- Slider -->
        <div class="row">
            <!--/Slider-->
            <div class="col-sm-6">
                <!-- Bottom switcher of slider -->
                <ul class="hide-bullets">
                    <li class="col-sm-3">
                        <a class="thumbnail" id="carousel-selector-0">
                            <img src="http://placehold.it/150x150&text=zero">
                        </a>
                    </li>

                    <li class="col-sm-3">
                        <a class="thumbnail" id="carousel-selector-1"><img src="http://placehold.it/150x150&text=1"></a>
                    </li>

                    <li class="col-sm-3">
                        <a class="thumbnail" id="carousel-selector-2"><img src="http://placehold.it/150x150&text=2"></a>
                    </li>

                    <li class="col-sm-3">
                        <a class="thumbnail" id="carousel-selector-3"><img src="http://placehold.it/150x150&text=3"></a>
                    </li>

                    <li class="col-sm-3">
                        <a class="thumbnail" id="carousel-selector-4"><img src="http://placehold.it/150x150&text=4"></a>
                    </li>

                    <li class="col-sm-3">
                        <a class="thumbnail" id="carousel-selector-5"><img src="http://placehold.it/150x150&text=5"></a>
                    </li>
                </ul>
            </div>
            
        </div>

    </div>
</div>
{% endblock content %}

templates/texttoppt_importfile.html
{% extends "base.html" %}
{% load i18n %}
<!-- use in forms -->
{% load bootstrap %} 

{% block meta_title %}{% trans "Convert Text to PPT" %}{% endblock %}

{% block extra_head %}

{% endblock %}
{% block content %}
<div class="container">

		<br>

		<h1>Convert your report outline to a PowerPoint presentation</h1>

		<hr>

		<div class="row form">

			<!-- end of col col-sm-6 -->
			<div class="col-sm-6 col-sm-offset-3">
				<small><i>(You can choose an existing file)</i></small>
				<form  role="form" method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
					<div class="form-group">
						<!-- <button type="submit" class = "btn btn-primary btn-block" role="button" data-toggle="modal" data-target="#downloadModal"><span class="glyphicon glyphicon-cloud-upload"></span> Convert to CSV</button> -->
							{% if messages %}
							{% for message in messages %}
							    <h4 {% if message.tags %} class="{{ message.tags }} text-align-center"{% endif %}>{{ message }}</h4>
							{% endfor %}
							{% endif %}

							{{ form_ImportFile | bootstrap}}
							<hr>
							<td>
								{{ form_TemplateOptions | bootstrap }}
							<td>

							<div id="user_template_div">
								{{ form_UserSlideTemplate | bootstrap }}
							</div>
							<!-- <div id="preloaded_template_div">
								{{ form_PreloadedSlideTemplate | bootstrap }}
							</div> -->
							<hr>
							<!-- <a href="{% url 'txttoppt:slide_templates' %}" class="btn btn-primary btn-block">Continue</a> -->
							<button type="submit" class = "btn btn-primary btn-block"><span class="glyphicon glyphicon-circle-arrow-right"></span> Convert to PowerPoint Presentation</button>				
					</div>	
				</form>

			</div>		
			<!-- end of col col-sm-6 -->
		</div>
		<!-- end of row form class -->
</div>
{% endblock content %}